import { Metadata } from "next";

export const metadata: Metadata = {
  title: "JSONPost vs Typeform – Best Free Typeform Alternative for Developers (2025)",
  description: "Looking for a fast, privacy-friendly Typeform alternative? JSONPost lets you build forms, automate workflows, and integrate with Google Sheets — free. Perfect for developers who need API access, unlimited embeds, and full data control.",
  keywords: [
    "free Typeform alternative for developers",
    "embed Typeform alternative on website", 
    "form builder with API access",
    "best form builder for SaaS apps",
    "Typeform vs JSONPost comparison",
    "API form builder",
    "embed form SDK",
    "form automation platform",
    "no-code form platform",
    "interactive form builder",
    "survey & feedback automation",
    "form workflow automation",
    "developer-friendly form builder",
    "white-label form solution",
    "unlimited form embeds",
    "form backend API",
    "conversational forms",
    "multi-step forms",
    "conditional logic forms",
    "webhook forms",
    "form integrations",
    "custom domains forms",
    "form data ownership",
    "privacy-focused forms"
  ],
  authors: [{ name: "JSONPost Team" }],
  creator: "JSONPost",
  publisher: "JSONPost",
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://jsonpost.com/free-typeform-alternative",
    title: "JSONPost vs Typeform – Best Free Typeform Alternative for Developers (2025)",
    description: "Looking for a fast, privacy-friendly Typeform alternative? JSONPost lets you build forms, automate workflows, and integrate with Google Sheets — free. Perfect for developers who need API access, unlimited embeds, and full data control.",
    siteName: "JSONPost",
    images: [
      {
        url: "/screenshots/typeform-style-forms-screenshot.png",
        width: 1200,
        height: 630,
        alt: "JSONPost - Free Typeform Alternative with Better Features",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "JSONPost vs Typeform – Best Free Typeform Alternative for Developers (2025)",
    description: "Looking for a fast, privacy-friendly Typeform alternative? JSONPost lets you build forms, automate workflows, and integrate with Google Sheets — free.",
    images: ["/og_images/typeform_alternatives_ogimage.png"],
    creator: "@jsonpost",
  },
  alternates: {
    canonical: "https://jsonpost.com/free-typeform-alternative",
  },
  category: "Web Development Tools",
};